# usage Brewfile
# `brew bundle` after `brew tap homebrew/bundle`
 
tap 'caskroom/homebrew-cask'
tap 'caskroom/versions'
tap 'homebrew/versions'
tap 'homebrew/binary'

brew 'openssl'
brew 'wget'
brew 'git'
brew 'gist'
brew 'gibo'
brew 'cmake'
brew 'curl'
brew 'nmap'
brew 'zsh'
brew 'zsh-completions'


cask 'airmail-beta'
cask 'appcleaner'
cask 'brackets'
cask 'cheatsheet'
cask 'dropbox'
cask 'filezilla'
cask 'flash'
cask 'google-chrome'
cask 'google-japanese-ime'
cask 'iterm2-beta'
cask 'java'
cask 'keepingyouawake'
cask 'kindle'
cask 'macvim'
cask 'minecraft'
cask 'night-owl'
cask 'phpstorm'
cask 'skype'
cask 'sublime-text3'
cask 'the-unarchiver'
cask 'virtualbox'
